title: Hardik Bansal # your name (or website title) here
logo: "/Profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below ( remove <br> elements if you don't need line breaks)
Engineer
 <br><br>
 <a href="mailto:hardik.guy@gamil.com">hardik.guy@gmail.com </a>
 <br>
 <a href="hardik-bansal-84a440159">LinkedIn </a>
 <br>
 <a href="https://github.com/bansal-hardik">Github </a>
 <br>
 <a href="https://leetcode.com/bansal_hardik/">LeetCode </a>

