title: Hardik Bansal # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Software-Firmware Engineer
  <br><br>
  <a href="mailto:hardik.guy@gmail.com">hardik.guy@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/hardik-bansal-84a440159/">LinkedIn Profile</a>
  <br>
  <a href="https://leetcode.com/bansal_hardik/">LeetCode </a>
theme: jekyll-theme-minimal

